### PR TITLE
Add optional transparency support and tidy memory management a bit

### PR DESCRIPTION
**Pull request by Hattshire**
To enable transparency, it needs to be build with
`$ make [...] enable_alpha=yes`
~Temporally, transparent colours are set in the form `rgba:ffff/ffff/ffff/ffff` (XRender colour notation)~

Related: #13 

__Edit__
Colour spec is now strictly `#RRGGBB` and `#RRGGBBAA` for simplicity.

### CODE REVIEW

**Comment by florentc** [comment]
Hello. Thank you very much for all your work on this significant pull request and implementing a much anticipated feature.

## Freeing color resources

Ok.

## Changes to memory management of the `Style` structure during config file parsing

I am not sure the proposed changes in how the config structure is managed are that benificial.

If I understand your intent correctly, you would like to manage a single mutable `Style style` variable, allocated dynamically and managed from `main.c`, and pass it by reference to procedures in `conf.c`. Right now, this is a regular automatic variable allocated in the stack, and it is passed by value to functions in `conf.c` in functional style. This requires a temp variable in `conf.c`, hence, temporary during the parsing, there are two `Style` in memory.

- I would rather stick to functional style as much as possible, and stack allocated variables.
- Dynamic allocation would make sense if we did not know what or how much to allocate before runtime. Here we know we will always need one `Style` structure. It seems to me there is no need for dynamic allocation here and we should allocate the variable in the stack.
- The temp variable `Style` may seem like a waste of memory in `parse_style_config`. I think it is acceptable: it only lives through this function, `Style` is small, and the whole config file parsing in an xob execution is done only once.
- I also do not feel the need to encapsulate the `Style` structure in `main` behind a `void*`

For these reasons (of course they remain open to discussion and I might have missed something important), I would like to stick to the current `Style` memory style structure management.

## General nitpicking remarks

We should harmonize `#ifdef ALPHA` and `ifndef ALPHA` for the sake of readability.
We should rework and clean the commit history before merging it.
We should clang-format the whole thing and check we follow usual naming conventions and style.
We should adapt the documentation.
We should check error-handling coverage.

I am just putting these here so that so don't forget.

## Main matter of the contribution: alpha channel support in color specifications through XRender

Since I am not familiar with XRender, you will have to guide me around the main matter of your contribution a little so I can dive in and maintain it confortably. Could you please describe, from a global viewpoint, the Xrender specific parts? Which are the main calls involved, etc. For now, I might make naive and incorrect comments. Do not hesitate to correct me.

In `display.c`, I don't think there should be a hard-coded `default_color` in `color_from_string`. Hard-coded defaults are centralized in `conf.h` for convenience and organisation. `xob` is intended to be defensive against user-modifiable config files, not its own hard-coded default `Style` structure. If the hard-coded defaults in `conf.h` were changed to invalid values, I don't think there would be any more guarantees that a duplicate hard-coded default in `display.c` would still be valid.

Can we do without reimplementing our own custom hex-color parser?

The adaptation of the Makefile and the abstraction with `Color` seem nice and clean. I am glad you preserved the possibility to compile the xlib only variant.

**Comment by Hattshire** [comment]
## Style memory
**NOTE**: `Style` structure is not modified in any mean, a new `Style_config` type is added as a pointer abstraction to libconfig's `config_t`, and thus not depending on `config_t` outside of `config.h`

The change was due to this:
https://github.com/florentc/xob/blob/ab37a1e042b8e87759bff1f0da5be36aaaa6df95/src/conf.c#L93-L102
A string is allocated while calling `config_setting_lookup_string(setting, name, &colorstring)`, and _libconfig_ is managing it's lifetime, so calling `config_destroy` on `parse_style_config` can mess up the content of the string, leaving a _non allocated questionable-content pointer_ for usage on the future colour parsing.

The way I found at that moment to manage the lifetime of that single string would have created a bunch of memory related changes that are not optimal for both simplicity and code readability, and `config_destroy` is necessary for a clean memory since `config_init` allocates some internal structures.

So `Style_config` (aka libconfig's `config_t`) should be freed at some point. (Since it would be used on `main`, I abstracted it for independence from `config_t` in case of a future libconfig drop).

Another solution that I think would be ideal is to move colour parsing to `conf.h`, as parsing the colour while reading the config file would remove the requirement to manage the `colorstring` lifetime outside conf.h scope, and thus `config_t` can be destroyed directly on `parse_style_config`, however I thought an api change of a whole function would be more intrusive than what I finally did.

Also maybe naming the type `Style_config` instead of something like `xob_config` was kind of a mistake, I wanted to stick to the rest of the file naming scheme, but maybe it's too confusing for that name similarity with the `Style` type.

## Ifdef and Ifndef
I began using Ifndef so the changed functions had the original function on top and the new alpha-compatible function on bottom. The only places on the source code that Ifdef is used is in display.c for 
* removing a warning for the unused `X_context x` argument on the alpha-compatible part (I think I can refactor it to make it more pleasing to read).
* finding an alpha-masked 32bit `XVisualInfo` for the correct functionality of XRender magic. (I think it would be good to transfer this to it's own function for readability, but I can't think of a way to get rid of the `Ifdef` there without duplicating code nor swapping the order of the functions, so I think I'll have to do the latter).

## Colour Parser
> Can we do without reimplementing our own custom hex-color parser?

I think that in order to maintain a solid compatibility between _alpha-compatible Styles_ and _pure-xlib builds_, an alpha-compatible colour parser implementation is needed on.
Due to passing `#rrggbbaa` to the xlib parser [will return 0](https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/d15c24c8/src/ParseCol.c#L57), and linking to XRender at all builds is not desired (nor it's ugly colour format, unless HDR is desired), I reduced the options to:
* Parse the last digits if the string begins with '#' and has a post-# length of 4, 8 or 16, parse the last -1, 2 or 4- digits, finally pass it to the xlib parser.
* Copy the "not-touched-in-12-years-will-not-change-anytime-soon" XParseColor implementation and add the above parse, parsing the colour once instead of twice.

## XRender
All XRender methods are prefixed with XRender, in the same style as Xlib calls are prefixed with X.
All XRender-dependant code is isolated from non-xrender code or pure-xlib implementations, aiming to modify the API as little as possible, so the code can be understandable in the same way as it was without xrender.
I think it would be nice to separate the Xlib and Xrender code from display.c to a new source file for a cleaner code.

## `default_color`
I think this is not needed, I used it while I was testing the alpha rendering and the `colorstring` cleanup, as black was not shouting "there_was_an_error" as that pinkish red does, but the original function returned NULL on parse error, so my bad for not restoring the default behaviour.

**Comment by Hattshire** [comment]
I uploaded my transparency-changes-only branch at Hattshire#4 if you're interested to see the early alpha changes without the memory management.

**Comment by florentc** [comment]
## Style memory and colour parser

Oh ok I see. I indeed got things totally mixed up and mistook `Style_config` for `Style`. My apologies.
Maybe we could also change `Colorspec` to three `char[8]` and `strncpy` the content of libconfig's parsed strings, but now considering the big picture of color parsing thanks to your explanations, I agree with you. Introducing the common color parser inspired by Xlib's in `conf.c`, and changing data representation of colors in `Style` to actual rgb(a) numeric values, is far more elegant, we won't have to deal with colorstrings outside of `conf.c` anymore, it is in line with each module's purpose, and easier to interface with either pure Xlib or XRender.

This is an internal change for the better that does not have any visible effect from the user's viewpoint so I am all for it.

## Getting `depth` and `visual`

I agree we should transfer the XRender search for 32bit visual to another function.

## Separation of Xlib and XRender code

What kind of decomposition did you have in mind?
* `display.c` (common xlib stuff) + `display-xlib.c` + `display-xrender.c`
* `display.c` (including xlib only stuff) + `display-xrender.c`
* `display.c` with separate `****_xlib` and `****_xrender` functions
* something else


Thank you again for your work on this pull request.

**Comment by Hattshire** [comment]
I'm stuck in the colour parser, the [XLib parser](https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/src/ParseCol.c) parses the following specs:
* _#RGB_
* _#RRGGBB_
* _#RRRGGGBBB_
* _#RRRRGGGGBBBB_

With _R, G_ and _B_ as a character in `[a-fA-F0-9]`. Otherwise it sends a _LookupColor_ request to the server for [server-side parsing](https://gitlab.freedesktop.org/xorg/app/rgb/-/blob/master/rgb.txt).

Sending a _LookupColor_ request from `conf.c`'s `parse_color()`, would need to have the _Display_ handle on `parse_style_config()`, and I don't know if you would like _display_ code on `conf.c` or not.

If you're curious about what's server-side parsed, see [freedesktop.org:xorg/app/rgb/rgb.txt](https://gitlab.freedesktop.org/xorg/app/rgb/-/blob/master/rgb.txt).

**Comment by Hattshire** [comment]
Also, would you like to support the other specs, or the typical _#RRGGBB_ is sufficient?

**Comment by florentc** [comment]
The typical #RRGGBB is enough. Keep it as simple as possible.

**Comment by florentc** [comment]
Hello,

Sorry for the long wait. I am about to merge your pull request, at last. A few last comments just for the sake of nitpicking:

## `conf.c`

Do you think there is actual benefit in declaring `color_spec_is_valid` and `parse_color` inline ?
In `color_spec_is_valid`, I think we should go standard, include `stdbool.h` and switch to type `bool` and constants `true` and `false`.

## `Makefile`

The makefile checks whether `enable_alpha` is defined. Since the README provides `enable_alpha=yes` as an example, this may suggest that `enable_alpha=no` disables the feature (which it does not). I think we should make this clearer.

The ALPHA macro is not used anywhere at the moment in the source files. Did you have a future specific use case in mind? (e.g. printing whether xob has been compiled with alpha in the usage text `-v`).

## `display_xrender.c`

This is the main matter of your contribution and is entirely your work. I think you deserve credit and should hold the copyright for this file if you do not mind putting your name instead. I also intend to credit you in other parts of the project: e.g. changelog and manpage. Is this ok?

## Commit history

Do not feel compelled to do this. If you find time and a way to do it, could you try to rebase the commit history into a shorter and more concise version.

Thank you again for your all your work. Note that these are just last minute details I can handle on my own before the next release.

**Comment by MuhammedZakir** [comment]
@florentc: maybe you can merge this?

**Comment by florentc** [comment]
I plan to. I need to cleanup the history beforehand and I am thinking about making xrender a dependency by default and building xob without it an option.

@Hattshire 
Would you mind holding the copyright for `display_xrender.c`? I am planning to change it to your name unless you object to this of course.
In any case I plan to give you attribution for the feature in the changelog.

**Comment by Hattshire** [comment]
I will check it 👌

**Comment by florentc** [comment]
After final adjustments and git history cleaning, your contribution just has been merged to the master branch 🎉

Thank you very much @Hattshire for your work and this long awaited feature!

**Comment by Hattshire** [comment]
🎉🎉

**Pull request closed without merging**
